cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    egil:
      email: egil@passionfruits.net
      failed_login_attempts: 0
      first_name: Egil
      last_name: Moller
      logged_in: false
      password: $2b$12$KE8gI/dTyiW9gpTbR9ab6u/JxNNHPr37.Ga1.yE5EFe6njvjZCmm2
      roles:
      - admin
      - editor
      - viewer
    espen:
      email: espen@passionfruits.net
      failed_login_attempts: 0
      first_name: Espen
      last_name: null
      logged_in: false
      password: $2b$12$h/cZLyemGKdpQXkj05WzSOWt6VUN84hsKUXhen7yYYLcvRCkgPFcm
      roles:
      - admin
      - editor
      - viewer
    geir:
      email: geir@passionfruits.net
      failed_login_attempts: 0
      first_name: Geir
      last_name: Isene
      logged_in: false
      password: $2b$12$bI/i6vuj05bV45HWy0moTuqT/e6tpkwwr6NS9VFXc9DIXv9NnEOZa
      roles:
      - admin
      - editor
      - viewer
    nicklas:
      email: niklas@passionfruits.net
      failed_login_attempts: 0
      first_name: Niklas
      last_name: Isene
      logged_in: false
      password: $2b$12$vPxeWkTvQGYQI9po8v7ksulFgaDeg8DC3aW77xi2RihhRmMKebDjW
      roles:
      - admin
      - editor
      - viewer
    saghar:
      email: saghar@passionfruits.net
      failed_login_attempts: 0
      first_name: Saghar
      last_name: Asadi
      logged_in: true
      password: $2b$12$sJYWKGKtTNQT1iDBgj3DtuPEv2yCI7Q.erxi3XefND0d5evS8K98O
      roles:
      - admin
      - editor
      - viewer
    siv:
      email: siv@passionfruits.net
      failed_login_attempts: 0
      first_name: Siv
      last_name: Bayegan
      logged_in: false
      password: $2b$12$rcZUaQojz4iXVmZf5Gh/du/Y8yPkqgYKFCrdpUETwIGxaPTpc5oYW
      roles:
      - admin
      - editor
      - viewer
pre-authorized:
  emails:
  - saghar@passionfruits.net
