cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    egil:
      email: egil@passionfruits.net
      failed_login_attempts: 0
      first_name: Egil
      last_name: Moller
      logged_in: false
      password: $2b$12$qpChv0fZjes6Io/1zOSfQ..v9JvZjv3Ihoan6cM/3NlBPGjB4PEeO
      roles:
      - admin
      - editor
      - viewer
    espen:
      email: espen@passionfruits.net
      failed_login_attempts: 0
      first_name: Espen
      last_name: null
      logged_in: false
      password: $2b$12$UUKsQ7klWFoVedZMe4ExseZ0NPtbAGXbt7NzC8YGZU57OJESZPiXy
      roles:
      - admin
      - editor
      - viewer
    geir:
      email: geir@passionfruits.net
      failed_login_attempts: 0
      first_name: Geir
      last_name: Isene
      logged_in: false
      password: $2b$12$1xU4mnzhEysv548lPFY9YO4J9X0WgBFzt7UEzO7jH.L8kFJJbC.di
      roles:
      - admin
      - editor
      - viewer
    niklas:
      email: niklas@passionfruits.net
      failed_login_attempts: 0
      first_name: Niklas
      last_name: Isene
      logged_in: false
      password: $2b$12$bnZUZSOCnDFGYmQiKrY7vO9/lPLK.l8nZmpL4spueOcbXZQZN6//W
      roles:
      - admin
      - editor
      - viewer
    saghar:
      email: saghar@passionfruits.net
      failed_login_attempts: 0
      first_name: Saghar
      last_name: Asadi
      logged_in: true
      password: $2b$12$8EnnpmjZrSripo9g.bodweAebj2mRN8Axza.SuWA91JFGQGU.oIYu
      roles:
      - admin
      - editor
      - viewer
    siv:
      email: siv@passionfruits.net
      failed_login_attempts: 0
      first_name: Siv
      last_name: Bayegan
      logged_in: false
      password: $2b$12$RSVZZXEuvDA1uNkNnBOueOKnhiZZZ4yUmL6FOEhlQ6N7JdvtXHbES
      roles:
      - admin
      - editor
      - viewer
pre-authorized:
  emails:
  - saghar@passionfruits.net

persistence:
  base: "file:./data"
